### ISSUE TITLE
Scene format?

### ISSUE THREAD

**Issue by ib00** [intel/RealTimePathTracingResearchFramework#1]
What format should the scene be in?

**Comment by jmengintel** [comment]
Thanks for reaching out!

The renderer currently expects custom formats for scene data and textures (.vks/.vkt). These are optimized for fast loading and for use with Vulkan. For example, .vkt stores MIP maps and is block compressed. The formats are implemented in libvkr: https://github.com/intel/RealTimePathTracingResearchFramework/tree/main/ext/libvkr

The easiest way to create .vks/.vkt files is using Blender:
https://github.com/intel/RealTimePathTracingResearchFramework/tree/main/ext/libvkr/scripts

It is also possible to add a custom loader for any other format to the Scene class, where the function `load_vkrs()` could serve as a reference:
https://github.com/intel/RealTimePathTracingResearchFramework/blob/main/librender/scene.cpp

In the future, we are also planning to add scene files, but there is currently no date for this.

**Comment by ib00** [comment]
Thanks! 

The first two links seem to be broken, but this works:
https://github.com/intel/RealTimePathTracingResearchFramework/tree/main/ext/libvkr/scripts

I'll give this a try.

**Comment by jmengintel** [comment]
Thanks, I've updated the links in the original post..
